//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public string Priority { get; set; }
        public System.DateTime DueDate { get; set; }
        public string TaskDescription { get; set; }
        public string TaskStatus { get; set; }

        
        public int ProjectID { get; set; }
        
        public int CollaboratorID { get; set; }

        [System.Runtime.Serialization.IgnoreDataMember]
        public virtual Collaborator Collaborator { get; set; }

        [System.Runtime.Serialization.IgnoreDataMember]
        public virtual Project Project { get; set; }
    }
}
